apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chekr.fullname" . }}
  labels:
    {{- include "chekr.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "list"
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "persistentvolumeclaims"
    verbs:
      - "get"
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
    verbs:
      - "*"
  - apiGroups:
      - "apps"
    resources:
      - "replicasets"
      - "deployments"
      - "daemonsets"
      - "statefulsets"
    verbs:
      - "get"
  - apiGroups:
      - "kyverno.io"
    resources:
      - "clusterpolicies"
    verbs:
      - "get"
      - "create"
      - "update"
      - "patch"
      - "delete"
