apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chekr.fullname" . }}
  labels:
    {{- include "chekr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
