{{- if .Values.ignoreRules }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  grype.yaml: |
{{ .Values.ignoreRules | indent 4 }}
{{- end }}
